import { useEffect, useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { Bot, Copy } from "lucide-react";
import { toast } from "sonner";
import { getIngestsThisMonth, type IngestRow } from "@/lib/hr.functions";
import { AuditReport } from "./ingest/AuditReport";
import { JsonTree, isRecord } from "./ingest/JsonTree";

type Tab = "report" | "fields" | "raw";
const TAB_LABEL: Record<Tab, string> = { report: "Report", fields: "All fields", raw: "Raw JSON" };

function copy(text: string, what: string) {
  navigator.clipboard
    .writeText(text)
    .then(() => toast.success(`${what} copied`))
    .catch(() => toast.error("Could not copy"));
}

function Meta({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="min-w-[120px]">
      <div className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</div>
      <div className="text-xs text-foreground">{children}</div>
    </div>
  );
}

export function ClaudeIngestCard() {
  const load = useServerFn(getIngestsThisMonth);
  const [rows, setRows] = useState<IngestRow[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [selected, setSelected] = useState(0);
  const [tab, setTab] = useState<Tab>("report");

  useEffect(() => {
    load()
      .then(setRows)
      .catch((e) => setError(e instanceof Error ? e.message : "Could not load Claude data."));
  }, [load]);

  const row = rows?.[selected];
  const payload: unknown = row?.payload;
  const raw = row ? JSON.stringify(payload, null, 2) : "";
  const isAudit = isRecord(payload) && payload["report"] === "monthly-kra-audit";
  const generated = isRecord(payload) && typeof payload["generated_at"] === "string" ? payload["generated_at"] : null;

  return (
    <div className="panel flex flex-col gap-4 p-5">
      <div className="flex flex-wrap items-center gap-2">
        <Bot className="h-4 w-4 text-primary" />
        <h3 className="text-sm font-semibold tracking-tight">Claude MCP data</h3>
        {rows && rows.length > 1 ? (
          <select
            value={selected}
            onChange={(e) => setSelected(Number(e.target.value))}
            className="ml-auto rounded-md border border-input bg-background px-2 py-1 text-xs"
            aria-label="Choose a received payload"
          >
            {rows.map((r, i) => (
              <option key={r.id} value={i}>
                {new Date(r.received_at).toLocaleString()}
                {isRecord(r.payload) && r.payload["status"] ? ` · ${String(r.payload["status"])}` : ""}
                {i === 0 ? " (latest)" : ""}
              </option>
            ))}
          </select>
        ) : null}
      </div>

      {error ? (
        <p className="text-xs text-danger">{error}</p>
      ) : rows === null ? (
        <p className="text-xs text-muted-foreground">Loading…</p>
      ) : !row ? (
        <p className="text-xs text-muted-foreground">Nothing received from Claude this month.</p>
      ) : (
        <>
          <div className="flex flex-wrap gap-x-6 gap-y-2 rounded-lg bg-muted/30 p-3">
            <Meta label="Received">{new Date(row.received_at).toLocaleString()}</Meta>
            {generated ? <Meta label="Generated by task">{new Date(generated).toLocaleString()}</Meta> : null}
            <Meta label="Source">{row.source}</Meta>
            <Meta label="Size">{(new Blob([raw]).size / 1024).toFixed(1)} KB</Meta>
            <Meta label="Receipt ID">
              <button
                type="button"
                className="inline-flex items-center gap-1 font-mono text-[11px] text-muted-foreground hover:text-foreground"
                onClick={() => copy(row.id, "Receipt ID")}
                title="Copy receipt ID"
              >
                {row.id.slice(0, 8)}… <Copy className="h-3 w-3" />
              </button>
            </Meta>
          </div>

          <div className="flex gap-1 border-b border-border/70">
            {(Object.keys(TAB_LABEL) as Tab[]).map((t) => (
              <button
                key={t}
                type="button"
                onClick={() => setTab(t)}
                className={`-mb-px border-b-2 px-3 py-1.5 text-xs font-medium ${
                  tab === t
                    ? "border-primary text-primary"
                    : "border-transparent text-muted-foreground hover:text-foreground"
                }`}
              >
                {TAB_LABEL[t]}
              </button>
            ))}
            {tab === "raw" ? (
              <button
                type="button"
                onClick={() => copy(raw, "JSON")}
                className="ml-auto inline-flex items-center gap-1 px-2 text-xs text-muted-foreground hover:text-foreground"
              >
                <Copy className="h-3 w-3" /> Copy JSON
              </button>
            ) : null}
          </div>

          {tab === "report" ? (
            isAudit ? (
              <AuditReport payload={payload as Record<string, unknown>} />
            ) : (
              <>
                <p className="text-xs text-muted-foreground">
                  This payload isn't a known report type, so it is shown field by field.
                </p>
                <JsonTree label="payload" value={payload} />
              </>
            )
          ) : tab === "fields" ? (
            <JsonTree label="payload" value={payload} />
          ) : (
            <pre className="max-h-[32rem] overflow-auto rounded bg-muted/40 p-3 text-[11px] leading-relaxed">
              {raw}
            </pre>
          )}
        </>
      )}
    </div>
  );
}
