/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiChangePasswordRouteImport } from './routes/api/change-password'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiDirectorRatingDetailsRouteImport } from './routes/api/director-rating-details'
import { Route as ApiDirectorRatingsRouteImport } from './routes/api/director-ratings'
import { Route as ApiReportCardRouteImport } from './routes/api/report-card'
import { Route as ApiPublicAttendanceSummaryRouteImport } from './routes/api/public/attendance-summary'
import { Route as ApiPublicRdashIngestRouteImport } from './routes/api/public/rdash-ingest'
import { Route as ApiPublicCronProcessQueueRouteImport } from './routes/api/public/cron/process-queue'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChangePasswordRoute = ApiChangePasswordRouteImport.update({
  id: '/api/change-password',
  path: '/api/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDirectorRatingDetailsRoute =
  ApiDirectorRatingDetailsRouteImport.update({
    id: '/api/director-rating-details',
    path: '/api/director-rating-details',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDirectorRatingsRoute = ApiDirectorRatingsRouteImport.update({
  id: '/api/director-ratings',
  path: '/api/director-ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportCardRoute = ApiReportCardRouteImport.update({
  id: '/api/report-card',
  path: '/api/report-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAttendanceSummaryRoute =
  ApiPublicAttendanceSummaryRouteImport.update({
    id: '/api/public/attendance-summary',
    path: '/api/public/attendance-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRdashIngestRoute = ApiPublicRdashIngestRouteImport.update({
  id: '/api/public/rdash-ingest',
  path: '/api/public/rdash-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronProcessQueueRoute =
  ApiPublicCronProcessQueueRouteImport.update({
    id: '/api/public/cron/process-queue',
    path: '/api/public/cron/process-queue',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/change-password': typeof ApiChangePasswordRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/director-rating-details': typeof ApiDirectorRatingDetailsRoute
  '/api/director-ratings': typeof ApiDirectorRatingsRoute
  '/api/report-card': typeof ApiReportCardRoute
  '/api/public/attendance-summary': typeof ApiPublicAttendanceSummaryRoute
  '/api/public/rdash-ingest': typeof ApiPublicRdashIngestRoute
  '/api/public/cron/process-queue': typeof ApiPublicCronProcessQueueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/change-password': typeof ApiChangePasswordRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/director-rating-details': typeof ApiDirectorRatingDetailsRoute
  '/api/director-ratings': typeof ApiDirectorRatingsRoute
  '/api/report-card': typeof ApiReportCardRoute
  '/api/public/attendance-summary': typeof ApiPublicAttendanceSummaryRoute
  '/api/public/rdash-ingest': typeof ApiPublicRdashIngestRoute
  '/api/public/cron/process-queue': typeof ApiPublicCronProcessQueueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/change-password': typeof ApiChangePasswordRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/director-rating-details': typeof ApiDirectorRatingDetailsRoute
  '/api/director-ratings': typeof ApiDirectorRatingsRoute
  '/api/report-card': typeof ApiReportCardRoute
  '/api/public/attendance-summary': typeof ApiPublicAttendanceSummaryRoute
  '/api/public/rdash-ingest': typeof ApiPublicRdashIngestRoute
  '/api/public/cron/process-queue': typeof ApiPublicCronProcessQueueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/change-password'
    | '/dashboard'
    | '/api/change-password'
    | '/api/dashboard'
    | '/api/director-rating-details'
    | '/api/director-ratings'
    | '/api/report-card'
    | '/api/public/attendance-summary'
    | '/api/public/rdash-ingest'
    | '/api/public/cron/process-queue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/change-password'
    | '/dashboard'
    | '/api/change-password'
    | '/api/dashboard'
    | '/api/director-rating-details'
    | '/api/director-ratings'
    | '/api/report-card'
    | '/api/public/attendance-summary'
    | '/api/public/rdash-ingest'
    | '/api/public/cron/process-queue'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/change-password'
    | '/_authenticated/dashboard'
    | '/api/change-password'
    | '/api/dashboard'
    | '/api/director-rating-details'
    | '/api/director-ratings'
    | '/api/report-card'
    | '/api/public/attendance-summary'
    | '/api/public/rdash-ingest'
    | '/api/public/cron/process-queue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChangePasswordRoute: typeof ApiChangePasswordRoute
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiDirectorRatingDetailsRoute: typeof ApiDirectorRatingDetailsRoute
  ApiDirectorRatingsRoute: typeof ApiDirectorRatingsRoute
  ApiReportCardRoute: typeof ApiReportCardRoute
  ApiPublicAttendanceSummaryRoute: typeof ApiPublicAttendanceSummaryRoute
  ApiPublicRdashIngestRoute: typeof ApiPublicRdashIngestRoute
  ApiPublicCronProcessQueueRoute: typeof ApiPublicCronProcessQueueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/change-password': {
      id: '/api/change-password'
      path: '/api/change-password'
      fullPath: '/api/change-password'
      preLoaderRoute: typeof ApiChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/director-rating-details': {
      id: '/api/director-rating-details'
      path: '/api/director-rating-details'
      fullPath: '/api/director-rating-details'
      preLoaderRoute: typeof ApiDirectorRatingDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/director-ratings': {
      id: '/api/director-ratings'
      path: '/api/director-ratings'
      fullPath: '/api/director-ratings'
      preLoaderRoute: typeof ApiDirectorRatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report-card': {
      id: '/api/report-card'
      path: '/api/report-card'
      fullPath: '/api/report-card'
      preLoaderRoute: typeof ApiReportCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/attendance-summary': {
      id: '/api/public/attendance-summary'
      path: '/api/public/attendance-summary'
      fullPath: '/api/public/attendance-summary'
      preLoaderRoute: typeof ApiPublicAttendanceSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rdash-ingest': {
      id: '/api/public/rdash-ingest'
      path: '/api/public/rdash-ingest'
      fullPath: '/api/public/rdash-ingest'
      preLoaderRoute: typeof ApiPublicRdashIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/process-queue': {
      id: '/api/public/cron/process-queue'
      path: '/api/public/cron/process-queue'
      fullPath: '/api/public/cron/process-queue'
      preLoaderRoute: typeof ApiPublicCronProcessQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChangePasswordRoute: ApiChangePasswordRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiDirectorRatingDetailsRoute: ApiDirectorRatingDetailsRoute,
  ApiDirectorRatingsRoute: ApiDirectorRatingsRoute,
  ApiReportCardRoute: ApiReportCardRoute,
  ApiPublicAttendanceSummaryRoute: ApiPublicAttendanceSummaryRoute,
  ApiPublicRdashIngestRoute: ApiPublicRdashIngestRoute,
  ApiPublicCronProcessQueueRoute: ApiPublicCronProcessQueueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
